apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-policy
  namespace: "${namespace}"
spec:
  egress:
    - {}
  ingress:
    - {}
  podSelector: {}
  policyTypes:
    - Egress
    - Ingress