apiVersion: v1
kind: Secret
metadata:
  namespace: ${namespace}
  name: ${secret_name}
data:
  username: ${kafka_user}
  password: ${kafka_pwd}
  ca.pem: ${kafka_ca_cert}
  sasl: ${sasl}
  tls: ${tls}
---